baseurl = "https://julianegrass.de"
copyright = "&copy; 2018 Juliane Graß"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disqusShortname = ""
enableEmoji = true
enableGitInfo = false
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = ""
hasCJKLanguage = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
preserveTaxonomyNames = true
theme = "academic"
title = "Juliane Graß"
[Languages.en]
languageCode = "en-us"
[blackfriday]
fractions = true
hrefTargetBlank = true
smartypants = true
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 2
[[menu.main]]
name = "Home"
url = "#about"
weight = 1
[outputs]
home = ["HTML", "CSS", "RSS"]
section = ["HTML", "RSS"]
[params]
avatar = "portrait.jpg"
color_theme = "default"
comment_count = true
custom_css = ["custom.css", "print.css"]
custom_js = ["init.js", "hyphenation.js"]
date_format = "Jan 2, 2006"
email = "info@julianegrass.de"
font = "default"
gravatar = false
highlight = true
highlight_languages = []
keybase = "julesz84"
latitude = "37.4275"
logo = ""
longitude = "-122.1697"
map = 0
map_api_key = ""
math = true
name = "Juliane Graß"
privacy_pack = true
publication_types = ["Uncategorized", "Conference proceedings", "Journal", "Work in progress", "Technical report", "Book", "Book chapter", "Workshop", "Thesis"]
reading_time = true
role = "Molecular Biologist"
section_pager = true
sharing = true
time_format = "3:04 PM"
zoom = 15
[params.menus]
align_right = true
[params.projects]
list_children = true
publication_format = 3
[params.publications]
date_format = "January, 2006"
[params.talks]
time = true
[[params.organizations]]
name = "TU Dresden"
url = "https://tu-dresden.de"
[[params.social]]
icon = "xing"
icon_pack = "fa"
link = "https://www.xing.com/profile/Juliane_Grass3"
[[params.social]]
icon = "researchgate"
icon_pack = "ai"
link = "https://www.researchgate.net/profile/Juliane_Grass"
[taxonomies]
category = "categories"
publication_type = "publication_types"
tag = "tags"
