[build]
  publish = "public"
  command = "hugo --config config.toml,user-config.toml"

[context.production.environment]
  HUGO_VERSION = "0.44"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
